swagger: "2.0"
info:
  description: API documentation for the Vacation App.
  version: 1.0.1
  title: Vacation App API
  contact:
    email: yo881251@ucf.edu
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

host: way-finder.xyz:5000
basePath: /
schemes:
  - http

paths:
  /api/register:
    post:
      tags:
        - Auth
      summary: Register a new user
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: user
          required: true
          schema:
            $ref: '#/definitions/Register'
      responses:
        200:
          description: Registration response

  /api/login:
    post:
      tags:
        - Auth
      summary: Login user
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: credentials
          required: true
          schema:
            $ref: '#/definitions/Login'
      responses:
        200:
          description: Login response

  /api/verify-email:
    get:
      tags:
        - Auth
      summary: Verify email with token
      produces:
        - text/html
      parameters:
        - in: query
          name: token
          required: true
          type: string
      responses:
        200:
          description: HTML confirmation

  /api/request-password-reset:
    post:
      tags:
        - Auth
      summary: Request password reset
      consumes:
        - application/json
      parameters:
        - in: body
          name: email
          required: true
          schema:
            $ref: '#/definitions/EmailOnly'
      responses:
        200:
          description: Password reset email sent

  /api/reset-password:
    post:
      tags:
        - Auth
      summary: Reset password with token
      consumes:
        - application/json
      parameters:
        - in: body
          name: reset
          required: true
          schema:
            $ref: '#/definitions/ResetPassword'
      responses:
        200:
          description: Password reset success

  /api/itinerary:
    post:
      tags:
        - Itinerary
      summary: Generate and save itinerary
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: itineraryRequest
          required: true
          schema:
            $ref: '#/definitions/ItineraryRequest'
        - in: header
          name: Authorization
          required: true
          type: string
      responses:
        200:
          description: Itinerary saved and returned

    delete:
      tags:
        - Itinerary
      summary: Delete an itinerary
      produces:
        - application/json
      parameters:
        - in: query
          name: created
          required: true
          type: string
        - in: header
          name: Authorization
          required: true
          type: string
      responses:
        200:
          description: Deletion confirmation

  /api/itineraries:
    get:
      tags:
        - Itinerary
      summary: Get user's itineraries
      produces:
        - application/json
      parameters:
        - in: header
          name: Authorization
          required: true
          type: string
      responses:
        200:
          description: List of itineraries

definitions:
  Register:
    type: object
    required:
      - firstName
      - lastName
      - login
      - password
    properties:
      firstName:
        type: string
        example: John
      lastName:
        type: string
        example: Doe
      login:
        type: string
        format: email
        example: yoanmolina15@gmail.com
      password:
        type: string
        example: Test123@

  Login:
    type: object
    required:
      - login
      - password
    properties:
      login:
        type: string
      password:
        type: string

  EmailOnly:
    type: object
    required:
      - email
    properties:
      email:
        type: string
        format: email

  ResetPassword:
    type: object
    required:
      - token
      - newPassword
    properties:
      token:
        type: string
      newPassword:
        type: string

  ItineraryRequest:
    type: object
    required:
      - location
      - startDate
      - duration
      - budget
      - interests
      - travelStyle
    properties:
      location:
        type: string
      startDate:
        type: string
        format: date
      duration:
        type: integer
      budget:
        type: number
      interests:
        type: array
        items:
          type: string
      travelStyle:
        type: string
