import { SuggestionLists } from "../types/Suggestions";

const SuggestionListsData: SuggestionLists = {
  location: [
      { value: "Amsterdam", relevance: 75 },
      { value: "Atlanta", relevance: 85 },
      { value: "Abu Dhabi", relevance: 65 },
      { value: "Berlin", relevance: 90 },
      { value: "Beijing", relevance: 70 },
      { value: "Boston", relevance: 80 },
      { value: "Charlotte", relevance: 55 },
      { value: "Chicago", relevance: 85 },
      { value: "Chengdu", relevance: 40 },
      { value: "Dallas", relevance: 80 },
      { value: "Delhi", relevance: 50 },
      { value: "Denver", relevance: 70 },
      { value: "Edmonton", relevance: 65 },
      { value: "Essen", relevance: 45 },
      { value: "Edinburgh", relevance: 35 },
      { value: "Fort Lauderdale", relevance: 80 },
      { value: "Florence", relevance: 70 },
      { value: "Fresno", relevance: 40 },
      { value: "Greensboro", relevance: 45 },
      { value: "Gothenburg", relevance: 35 },
      { value: "Geneva", relevance: 25 },
      { value: "Houston", relevance: 70 },
      { value: "Honolulu", relevance: 80 },
      { value: "Hamburg", relevance: 70 },
      { value: "Indianapolis", relevance: 65 },
      { value: "Istanbul", relevance: 55 },
      { value: "Ironville	", relevance: 15 },
      { value: "Jakarta", relevance: 10 },
      { value: "Jacksonville", relevance: 20 },
      { value: "Jersey City", relevance: 30 },
      { value: "Kyoto", relevance: 65 },
      { value: "Katowice", relevance: 35 },
      { value: "Kansas City", relevance: 55 },
      { value: "Los Angeles", relevance: 95 },
      { value: "London", relevance: 75 },
      { value: "Las Vegas", relevance: 50 },
      { value: "Miami", relevance: 75 },
      { value: "Macau", relevance: 35 },
      { value: "Manchester", relevance: 25 },
      { value: "Nashville", relevance: 60 },
      { value: "Nairobi", relevance: 10 },
      { value: "New York", relevance: 100 },
      { value: "Oslo", relevance: 75 },
      { value: "Orlando", relevance: 95 },
      { value: "Osaka", relevance: 25 },
      { value: "Prague", relevance: 40 },
      { value: "Panama", relevance: 80 },
      { value: "Paris", relevance: 90 },
      { value: "Quebec", relevance: 15 },
      { value: "Quezon City", relevance: 65 },
      { value: "Rome", relevance: 60 },
      { value: "Reykjavik", relevance: 20 },
      { value: "San Francisco", relevance: 95 },
      { value: "Shanghai", relevance: 50 },
      { value: "Seoul", relevance: 75 },
      { value: "Tokyo", relevance: 80 },
      { value: "Toronto", relevance: 50},
      { value: "Tacoma", relevance: 10},
      { value: "Tirana", relevance: 70 },
      { value: "Utrecht", relevance: 75 },
      { value: "Ulaanbaatar", relevance: 65 },
      { value: "Vancouver", relevance: 90 },
      { value: "Vientiane", relevance: 60 },
      { value: "Venice", relevance: 66},
      { value: "Valencia", relevance: 52},
      { value: "Washington", relevance: 85 },
      { value: "Wellington", relevance: 80 },
      { value: "Xiamen", relevance: 60 },
      { value: "Xalapa", relevance: 50 },
      { value: "Yokohama", relevance: 55 },
      { value: "Yerevan", relevance: 25 },
      { value: "Zurich", relevance: 30 },
      { value: "Zagreb", relevance: 40 }            
  ],
  budget: [
    {value: 'low', relevance: 1},
    {value: 'medium', relevance: 1},
    {value: 'high', relevance: 1},
  ],
  interests: [
    {value: 'adventure', relevance: 1},
    {value: 'culture', relevance: 1},
    {value: 'relaxation', relevance: 1},
  ],
  travelStyle: [
    {value: 'solo', relevance: 1},
    {value: 'family', relevance: 1},
    {value: 'luxury', relevance: 1},
    {value: 'backpacking', relevance: 1},
  ],
};

export { SuggestionListsData };